

@token = 9d4ebc79-81c5-425b-88f8-668909d300c5
@q = [["name","like", "usu"]]

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
GET http://localhost:3000/session
Authorization: {{token}}

###
GET http://localhost:3000/logout
Authorization: {{token}}

###
GET http://localhost:3000/api/res.partner
Authorization: {{token}}

###
GET http://localhost:3000/api/res.partner?q={{q}}
Authorization: {{token}}

###
GET http://localhost:4000/api/res.partner/10?token={{token}}

###
POST http://localhost:3000/api/res.partner?token={{token}}
Content-Type: application/json

{
    "name": "Carlos Navarrete"
}

###
PATCH http://localhost:3000/api/res.partner/10
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Alverto Navarrete"
}

###
DELETE http://localhost:3000/api/res.partner/10
Authorization: {{token}}