

@token = 0509920b-17ea-45d6-b7ba-dd6ac42b9bb2
@q = [["name","like", "usu"]]

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "admin",
    "password": "123456"
}

###
GET http://localhost:3000/session
Authorization: {{token}}

###
GET http://localhost:3000/logout
Authorization: {{token}}

###
GET http://localhost:3000/api/res.partner
Authorization: {{token}}

###
GET http://localhost:3000/api/res.partner?q={{q}}
Authorization: {{token}}

###
GET http://localhost:3000/api/res.partner/10
Authorization: {{token}}

###
POST http://localhost:3000/api/res.partner
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Carlos Navarrete"
}

###
PATCH http://localhost:3000/api/res.partner/10
Authorization: {{token}}
Content-Type: application/json

{
    "name": "Alverto Navarrete"
}

###
DELETE http://localhost:3000/api/res.partner/10
Authorization: {{token}}